services:
    db:
        container_name: miage-mariadb
        image: mariadb:10.7
        working_dir: /application
        command:
            [
                mysqld,
                --character-set-server=utf8mb4,
                --collation-server=utf8mb4_unicode_ci,
                --innodb-file-per-table=1,
            ]
        volumes:
            - ./.docker/mariadb/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root-user
            - MYSQL_DATABASE=miage-db
            - MYSQL_USER=miage-user
            - MYSQL_PASSWORD=miage-pwd
    nginx:
        container_name: miage-nginx
        image: nginx:alpine
        ports:
            - "8050:80"
        volumes:
            - ./www:/var/www/html:ro
            - ./.docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php
    php:
        container_name: miage-php
        image: miage-php-img:v1
        build:
          context: .docker/php/
          dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./www:/var/www/html
            - .docker/php/conf/zzzz_custom.ini:/usr/local/etc/php/conf.d/zzzz_custom.ini
        extra_hosts:
          - "host.docker.internal:host-gateway"